server.port=5000

# Configuración para usar una base de datos embebida SQLite local en la ruta persistente
spring.datasource.url=jdbc:sqlite:/app/data/inventario.db
spring.datasource.driver-class-name=org.sqlite.JDBC